# Generated by Django 4.0 on 2021-12-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(help_text='Eg- ISE', max_length=4)),
                ('semester', models.CharField(help_text='Eg- 1 semester', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
